FROM python:3.12-slim

WORKDIR /app

# COPY pyproject.toml .

COPY worker ./worker

COPY termtrix_common ./termtrix_common

# Install shared package
RUN pip install --no-cache-dir -e ./termtrix_common

# RUN pip install -e .

CMD ["python", "-m", "worker.clickhouse_writer"]


